Repository AY2425S2-CS2103T-T11-3/tp, pull requests merged in 2025-03, with the labels that each got.

#38 Adding Feature 1 CRUD for Staff
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Block.java
  src/main/java/seedu/address/model/person/Designation.java
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Room.java
  src/main/java/seedu/address/model/person/Staff.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/BlockTest.java
  src/test/java/seedu/address/model/person/DesignationTest.java
  src/test/java/seedu/address/model/person/LevelTest.java
  src/test/java/seedu/address/model/person/RoomTest.java
  src/test/java/seedu/address/model/person/StaffTest.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
Labels: priority.High

#41 Adding Feature 1: View Staff List
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/ListStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ListType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/UniqueStaffList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/main/java/seedu/address/ui/StaffListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StaffListCard.fxml
  src/main/resources/view/StaffListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/ListStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniqueStaffListTest.java
Labels: priority.High

#44 Add Feature 1: Add Student
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Matric.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/StudentDesignation.java
  src/test/java/seedu/address/model/person/MatricTest.java
  src/test/java/seedu/address/model/person/StudentDesignationTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: priority.High

#39 Add AddExternalCommand class
  README.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddExternalCommand.java
  src/main/java/seedu/address/logic/parser/AddExternalCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/ExternalParty.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddExternalCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddExternalCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/ExternalPartyBuilder.java
Labels: priority.High

#42 Add Event CRUD Feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventEndTime.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/EventStartTime.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#45 Add Feature 2: Search Staff
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/SearchStaffCommandParser.java
  src/main/java/seedu/address/model/person/StaffMatchesAttributesPredicate.java
Labels: priority.Medium

#46 Feature 4: Search for events going on in the residences
  src/main/java/seedu/address/logic/commands/event/SearchEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchEventCommandParser.java
  src/main/java/seedu/address/model/event/EventStartTime.java
Labels: priority.Medium

#60 Feature 2: Fix search staff
  src/main/java/seedu/address/logic/parser/SearchStaffCommandParser.java
  src/main/java/seedu/address/model/person/StaffMatchesAttributesPredicate.java
Labels: priority.Medium

#79 Feature 1: Student - Delete
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentCommandParserTest.java
Labels: priority.High

#80 Feature 1: Student Storage
  src/main/java/seedu/address/model/person/StudentDesignation.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/model/person/StaffDesignationTest.java
  src/test/java/seedu/address/model/person/StudentDesignationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High

#82 Feature 1: Staff - Storage
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/StaffDesignation.java
  src/main/java/seedu/address/model/person/StaffMatchesAttributesPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedStaff.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/test/java/seedu/address/model/person/StaffDesignationTest.java
  src/test/java/seedu/address/model/person/StudentDesignationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStaffTest.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
  src/test/java/seedu/address/testutil/TypicalStaffs.java
Labels: priority.High

#84 Feature 2: Search External
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchExternalPartyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchExternalPartyCommandParser.java
  src/main/java/seedu/address/model/person/ExternalPartyMatchesAttributesPredicate.java
  src/test/java/seedu/address/logic/commands/SearchExternalPartyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchExternalPartyCommandParserTest.java
  src/test/java/seedu/address/model/person/ExternalPartyMatchesAttributesPredicateTest.java
Labels: priority.High

#86 Feature 1: External Parties - Delete
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteExternalPartyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteExternalPartyCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteExternalPartyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteExternalPartyCommandParserTest.java
Labels: priority.High

#87 Feature 1: External Parties - Storage
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/storage/JsonAdaptedExternalParty.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/resources/view/ExternalPartyListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedExternalPartyTest.java
  src/test/java/seedu/address/testutil/TypicalExternalParties.java
Labels: priority.High

#99 Add view_event command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewEventCommandParser.java
  src/main/java/seedu/address/model/ListType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventEndTime.java
  src/main/java/seedu/address/ui/EventDetailPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventDetailPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ListEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ViewEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewEventCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventEndTimeTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventParticipantTest.java
  src/test/java/seedu/address/model/event/EventStartTimeTest.java
  src/test/java/seedu/address/model/event/EventTest.java
Labels: priority.High

#97 add event test coverage
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewEventCommandParser.java
  src/main/java/seedu/address/model/ListType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventEndTime.java
  src/main/java/seedu/address/ui/EventDetailPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventDetailPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ListEventCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ViewEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewEventCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventEndTimeTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventParticipantTest.java
  src/test/java/seedu/address/model/event/EventStartTimeTest.java
  src/test/java/seedu/address/model/event/EventTest.java
Labels: priority.High

#108 Feature 1 Bug Fix: Adding External Party Identity Check
  src/main/java/seedu/address/logic/commands/AddExternalCommand.java
  src/main/java/seedu/address/model/person/ExternalParty.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddExternalCommandTest.java
  src/test/java/seedu/address/model/person/ExternalPartyTest.java
  src/test/java/seedu/address/model/person/UniqueExternalPartyListTest.java
Labels: priority.High

#109 Branch delete event member command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/event/AddEventMemberCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventMemberCommand.java
  src/main/java/seedu/address/logic/parser/AddEventMemberCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteEventMemberCommandParser.java
  src/test/java/seedu/address/logic/commands/event/AddEventMemberCommandTest.java
  src/test/java/seedu/address/logic/commands/event/DeleteEventMemberCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventMemberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventMemberCommandParserTest.java
Labels: priority.High

#115 Requirement: Enable Assertions
  build.gradle
Labels: priority.High

#118 Update UserGuide
  docs/UserGuide.md
Labels: priority.Low

#120 update UserGuide on list_event, add_event, delete_event, view_event
  docs/UserGuide.md
Labels: priority.High

#121 Update user guide for delete_ext, search_stu, search_staff, search_ext
  docs/UserGuide.md
Labels: priority.High

#122 Update UserGuide
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.Low

#123 Ensuring Consistency in naming of External Party
  src/main/java/seedu/address/logic/commands/AddExternalPartyCommand.java
  src/main/java/seedu/address/logic/parser/AddExternalPartyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddExternalPartyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddExternalPartyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddExternalPartyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium

#124 Final Readme Updates
  docs/UserGuide.md
Labels: priority.High

#125 Edit error message for duplicate staff
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
Labels: priority.Low

#127 Features 1 and 3: Integration for Deletion of Staff
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListIntegrationTest.java
Labels: priority.High

#129 Features 1 and 3: Integration for Deletion of External Parties
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListIntegrationTest.java
Labels: priority.High

#128 Features 1 and 3: Integration for Deletion of Students
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListIntegrationTest.java
Labels: priority.High

#117 Adding UML Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/UpdatedModelClassDiagram.puml
Labels: priority.Medium

#126 Update test cases regarding SearchEvent command
  src/main/java/seedu/address/logic/commands/event/SearchEventCommand.java
  src/main/java/seedu/address/logic/parser/SearchEventCommandParser.java
  src/test/java/seedu/address/logic/parser/SearchEventCommandParserTest.java
  src/test/java/seedu/address/model/event/EventMatchesPredicateTest.java
Labels: priority.Medium

#132 Search for person in events
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/event/SearchEventMemberCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SearchEventMemberCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventMemberPredicate.java
  src/main/java/seedu/address/ui/EventDetailPanel.java
  src/test/java/seedu/address/logic/commands/SearchStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/event/SearchEventMemberCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchEventMemberCommandParserTest.java
  src/test/java/seedu/address/model/event/EventMemberPredicateTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: priority.High

#133 UML Diagram: Delete Sequence Diagrams for Student, Staff, External Party
  docs/diagrams/DeleteExternalPartySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteStaffSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
Labels: priority.Medium

#136 add UML sequence diagram for adding event and deleting event
  docs/diagrams/AddEventSequenceDiagram.puml
  docs/diagrams/DeleteEventSequenceDiagram.puml
Labels: priority.Medium
