Repository AY2425S2-CS2103T-T11-3/tp, pull requests merged in 2025-04, with the labels that each got.

#146 fix UI listing problem
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#130 Fix event equals method
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/person/UniqueExternalPartyList.java
  src/main/java/seedu/address/model/person/UniqueStaffList.java
  src/main/java/seedu/address/model/person/UniqueStudentList.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/person/UniqueExternalPartyListTest.java
  src/test/java/seedu/address/model/person/UniqueStaffListTest.java
  src/test/java/seedu/address/model/person/UniqueStudentListTest.java
Labels: type.Bug

#144 update clear command in userguide
  docs/UserGuide.md
Labels: priority.Low

#165 Fix cosmetic error
  src/main/java/seedu/address/logic/commands/AddExternalPartyCommand.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#164 Fix cosmetic error
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#163 Fix cosmetic error
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#149 Fix Student Tag
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
Labels: type.Bug, alpha-bug

#150 Fix Staff Tags
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
Labels: type.Bug, alpha-bug

#167 Fix for persons appearing in multiple lists
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddExternalPartyCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueExternalPartyList.java
  src/main/java/seedu/address/model/person/UniqueStaffList.java
  src/main/java/seedu/address/model/person/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddExternalPartyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddExternalPartyCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
Labels: priority.High, alpha-bug

#159 Add padding to StudentListCard
  src/main/resources/view/StudentListCard.fxml
Labels: severity.VeryLow, alpha-bug

#161 Add padding to StaffListCard
  src/main/resources/view/StaffListCard.fxml
Labels: severity.VeryLow, alpha-bug

#175 Bug Fix: Updated error message for level and room
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Room.java
Labels: type.Bug, severity.Low, alpha-bug

#135 Add sequence diagram for SearchEventMemberCommand and SearchEventCommand
  docs/diagrams/SearchEventCommandSequenceDiagram.puml
  docs/diagrams/SearchEventMemberCommandSequenceDiagram.puml
Labels: priority.Medium

#179 Bug Fix: Search stu, staff, ext now displays number and attributes in message log
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchExternalPartyCommand.java
  src/main/java/seedu/address/logic/commands/SearchStaffCommand.java
  src/main/java/seedu/address/logic/commands/SearchStudentCommand.java
  src/test/java/seedu/address/logic/commands/SearchExternalPartyCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchStudentCommandTest.java
Labels: type.Bug, severity.Low, alpha-bug

#181 Bug Fix: Search event and event member message logs updated for consistency
  src/main/java/seedu/address/logic/commands/event/SearchEventCommand.java
  src/main/java/seedu/address/logic/commands/event/SearchEventMemberCommand.java
Labels: type.Bug, severity.Low, alpha-bug

#143 Fix add duplicate member in event
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/event/AddEventMemberCommand.java
  src/test/java/seedu/address/logic/commands/event/AddEventMemberCommandTest.java
Labels: alpha-bug

#177 Bug Fix: Fixed bug where field after prefix is empty
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/parser/SearchEventCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchEventMemberCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchExternalPartyCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchStudentCommandParser.java
  src/test/java/seedu/address/logic/parser/SearchEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchEventMemberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchExternalPartyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchStudentCommandParserTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#178 standardization: commands will take members from the full list
  src/main/java/seedu/address/logic/commands/DeleteExternalPartyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/event/AddEventMemberCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/event/DeleteEventMemberCommand.java
  src/main/java/seedu/address/logic/commands/event/SearchEventMemberCommand.java
  src/main/java/seedu/address/logic/commands/event/ViewEventCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteExternalPartyCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
Labels: alpha-bug

#182 Bug Fix: Update `EventMatchesPredicate` to fullSearch criteria and error handle empty field after prefices in `SearchEventMemberCommand`
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/event/SearchEventCommand.java
  src/main/java/seedu/address/logic/commands/event/SearchEventMemberCommand.java
  src/main/java/seedu/address/model/event/EventMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/event/SearchEventCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchEventMemberCommandParserTest.java
  src/test/java/seedu/address/model/event/EventMatchesPredicateTest.java
Labels: alpha-bug

#187 update userguide
  docs/UserGuide.md
  docs/images/add_event_memberSuccess.png
  docs/images/add_extSuccess.png
  docs/images/add_staffSuccess.png
  docs/images/delete_event_memberSuccess.png
  docs/images/delete_stuSuccess.png
  docs/images/list_stuSuccess.png
  docs/images/search_stuSuccess.png
  docs/images/view_eventSuccess.png
Labels: alpha-bug

#239 Update ug to describe how duplicates are detected
  docs/UserGuide.md
Labels: type.Bug

#233 Update data file and build file to be Resiconnect
  build.gradle
  src/main/java/seedu/address/model/UserPrefs.java
Labels: type.Bug

#234 Accept leading zeroes for level
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Level.java
  src/test/java/seedu/address/model/person/LevelTest.java
Labels: type.Bug

#236 Allow room to have leading zeroes
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Room.java
  src/test/java/seedu/address/model/person/RoomTest.java
Labels: type.Bug

#237 Remove multiple whitespaces in address
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Address.java
  src/test/java/seedu/address/model/person/AddressTest.java
Labels: type.Bug

#230 bug fix - fix event
  src/main/java/seedu/address/logic/commands/event/AddEventCommand.java
  src/main/java/seedu/address/model/event/EventName.java
  src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java
Labels: type.Bug

#240 bug fix - person name that include exceptions
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExternalPartyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStaffTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: type.Bug

#243 Add confirmation of number of residents in a room to future version planning
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug
